### ISSUE TITLE
Error: .onLoad failed in loadNamespace() for 'checkmate',

### ISSUE THREAD

**Issue by felkhider** [frankfarach/npi#20]
Thanks for package.
Now getting an error: Error: .onLoad failed in loadNamespace() for 'checkmate',

**Comment by frankfarach** [comment]
Thanks for reporting this issue. Can you please provide a [minimum reproducible example](https://robjhyndman.com/hyndsight/minimal-reproducible-examples/), or [reprex](https://reprex.tidyverse.org/), of the error?
