### ISSUE TITLE
Error with npi_search

### ISSUE THREAD

**Issue by trang-n** [frankfarach/npi#74]
Hi @frankfarach, thanks for a very useful package!
I encountered this error today while running npi_search. Would appreciate any insights!

```
> nyc <- npi_search(city = "New York City")
Requesting records 0-10...
Error in `npi_handle_response()`:
! API returned text/plain, not JSON.
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by trang-n** [comment]
I investigated this more today and looks like they changed the API output format to text.

**Comment by frankfarach** [comment]
Hi @trang-n, thanks for identifying this issue! I was able to replicate the problem and agree with your diagnosis. I will dig into this further in the next few days and hopefully get the issue resolved soon.

**Comment by trang-n** [comment]
Thank you @frankfarach!

**Comment by parmsam** [comment]
@frankfarach, added possible solution in PR.

**Comment by frankfarach** [comment]
Thanks, @parmsam! I will review it by the end of this week. I appreciate your help.
